name: Integración Continua (CI)
on:
  push:
    branches: [ main ]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18', '20']
        
    steps:
      - name: 1 obtener codigo
        uses: actions/checkout@v4
        
      - name: 2 configurar node.jd(20)
        uses: actions/setup-node@v4
        with: 
          node-version: ${{ matrix.node-version }}
          
      - name: 3 instalar dependencias
        run: npm ci
        
      - name: 4 probar el codigo
        run: npm test

  deploy:
     runs-on: ubuntu-latest
     needs: [build_and_test]
     
     steps:
       - name: 1. Descargar Código para Despliegue
         uses: actions/checkout@v4

       - name: 2. Despliegue
         run: echo "Despliegue exitoso."
         env:
           API_STATUS: OK
